Use Elixir's mix tasks instead of /bin/ scripts
fs/elixir-base pull request #25
Opened 2017-03-15 10:44 UTC by slavakisel

closes #24

2017-03-15 11:53 UTC, ghost requested changes

2017-03-15 11:53 UTC, AlexeyKuznetzov commented on lib/mix/tasks/deploy.ex
> +  def run(["production"]) do
Please prefer single-line syntax `def func, do: ...`

2017-03-15 11:53 UTC, AlexeyKuznetzov commented on lib/mix/tasks/deploy.ex
> +    IO.puts("Deploying #{dest} to #{branch}")
Should we use logger instead of IO?

2017-03-15 11:53 UTC, AlexeyKuznetzov commented on lib/mix/tasks/deploy.ex
> +    build(dest, branch) |> release(dest) |> start(dest)
Pipelines should start from single argument:
```
dest |> build(branch) |> release(dest) |> start(dest)
```

2017-03-15 11:53 UTC, AlexeyKuznetzov commented on lib/mix/tasks/deploy.ex
> +  defp release(prev_status, dest) do
You can use guard clause here for prev_status

2017-03-15 11:53 UTC, AlexeyKuznetzov commented on lib/mix/tasks/deploy.ex
> +  defp start(prev_status, dest) do
The same guard clause can be used here

2017-03-15 11:53 UTC, AlexeyKuznetzov commented on lib/mix/tasks/run_espec.ex
> +    Mix.Shell.cmd("MIX_ENV='test' mix espec --format=doc", fn(output) -> IO.write(output) end)
"MIX_ENV='test' mix espec --format=doc" |> Mix.Shell.cmd(&IO.write/1)

2017-03-15 11:53 UTC, AlexeyKuznetzov commented on mix.exs
> +      ci: ["run_espec", "quality"],
~w(run_espec quality)

2017-03-15 11:53 UTC, AlexeyKuznetzov commented on lib/mix/tasks/run_espec.ex
> +defmodule Mix.Tasks.RunEspec do
Why not to name it just Espec?

2017-03-15 13:07 UTC, slavakisel commented on lib/mix/tasks/run_espec.ex
> +defmodule Mix.Tasks.RunEspec do
Didn't want name confusion because there is already existent `espec` task in test environment

2017-03-15 13:09 UTC, AlexeyKuznetzov commented on lib/mix/tasks/run_espec.ex
> +defmodule Mix.Tasks.RunEspec do
OK

2017-03-16 15:30 UTC, ghost approved these changes
Nice :shipit:

2017-03-16 15:30 UTC, merged